// <auto-generated>
// This code was auto-generated by a tool, every time
// the tool executes this code will be reset.
//
// If you need to extend the classes generated to add
// fields or methods to them, please create partial  
// declarations in another file.
// </auto-generated>
namespace Quantum {
  using UnityEngine;


  [UnityEngine.DisallowMultipleComponent]
  public partial class QPrototypeTransform2DVertical : Quantum.QuantumUnityComponentPrototype<Quantum.Prototypes.Transform2DVerticalPrototype>, 
    IQuantumUnityPrototypeWrapperForComponent<Quantum.Transform2DVertical> {
    
    [DrawInline, ReadOnly(InEditMode = false)]
    public Quantum.Prototypes.Transform2DVerticalPrototype Prototype = new();
    
    public override System.Type ComponentType => typeof(Quantum.Transform2DVertical);
    
    public override Quantum.ComponentPrototype CreatePrototype(Quantum.QuantumEntityPrototypeConverter converter) => base.ConvertPrototype(converter, Prototype);
  }
}